/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * accesorios.java
 *
 * Created on 17/03/2011, 02:03:46 PM
 */

/**
 *
 * @author alumno
 */
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.awt.Color;
import javax.swing.*;
import java.util.Calendar;
public class NOTA_VENTA extends javax.swing.JInternalFrame {

    int cont;
    private DefaultListModel modelo1= new DefaultListModel();
    private DefaultListModel modelo2= new DefaultListModel();
    private String numfac="";
    private String nombreemp="";
    private String nombrecliente="";
    private String dire="";
    private String ndni="";
    private String preciou="";
    private String encabezado="";
    /** Creates new form accesorios */
    public NOTA_VENTA() {
        initComponents();

        this.jComboBox1.setSelectedIndex(-1);
        jList3.setModel(modelo1);
        jList4.setModel(modelo2);
         this.jButton4.setEnabled(false);
        this.jButton5.setEnabled(false);
        this.listcolec.setVisible(false);
        this.listcolpre.setVisible(false);
        this.listcollar.setVisible(false);
        this.listprecollar.setVisible(false);
        this.listpendientes.setVisible(false);
        this.listprependi.setVisible(false);
        this.listanillos.setVisible(false);
        this.listpreanillos.setVisible(false);
        
        //imagenes
        this.li1.setVisible(false);
        this.li2.setVisible(false);
        this.li3.setVisible(false);
        this.li4.setVisible(false);
        this.li5.setVisible(false);
        this.lj1.setVisible(false);
        this.lj2.setVisible(false);
        this.lj3.setVisible(false);
        this.lj4.setVisible(false);
        this.lj5.setVisible(false);
        this.lk1.setVisible(false);
        this.lk2.setVisible(false);
        this.lk3.setVisible(false);
        this.lk4.setVisible(false);
        this.lk5.setVisible(false);
        this.lm1.setVisible(false);
        this.lm2.setVisible(false);
        this.lm3.setVisible(false);
        this.lm4.setVisible(false);
        this.lm5.setVisible(false);



        //contador
        JOptionPane.showMessageDialog(null,"-- HACER NOTA DE VENTA --" +"\n");
        cont = 001;
        txtnro.setText("00"+cont);
        
         
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chooser = new javax.swing.JFileChooser();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listcolec = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtpre = new javax.swing.JTextField();
        txtnro = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listcolpre = new javax.swing.JList();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList();
        jScrollPane5 = new javax.swing.JScrollPane();
        jList4 = new javax.swing.JList();
        jLabel13 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        listcollar = new javax.swing.JList();
        jScrollPane7 = new javax.swing.JScrollPane();
        listprecollar = new javax.swing.JList();
        jScrollPane8 = new javax.swing.JScrollPane();
        listpendientes = new javax.swing.JList();
        jScrollPane9 = new javax.swing.JScrollPane();
        listprependi = new javax.swing.JList();
        jScrollPane10 = new javax.swing.JScrollPane();
        listanillos = new javax.swing.JList();
        jScrollPane11 = new javax.swing.JScrollPane();
        listpreanillos = new javax.swing.JList();
        jLabel10 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        lbldate = new javax.swing.JLabel();
        lblhora = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        li1 = new javax.swing.JLabel();
        li2 = new javax.swing.JLabel();
        li3 = new javax.swing.JLabel();
        li5 = new javax.swing.JLabel();
        li4 = new javax.swing.JLabel();
        lj1 = new javax.swing.JLabel();
        lj2 = new javax.swing.JLabel();
        lj3 = new javax.swing.JLabel();
        lj4 = new javax.swing.JLabel();
        lj5 = new javax.swing.JLabel();
        lk1 = new javax.swing.JLabel();
        lk2 = new javax.swing.JLabel();
        lk3 = new javax.swing.JLabel();
        lk4 = new javax.swing.JLabel();
        lk5 = new javax.swing.JLabel();
        lm1 = new javax.swing.JLabel();
        lm2 = new javax.swing.JLabel();
        lm3 = new javax.swing.JLabel();
        lm4 = new javax.swing.JLabel();
        lm5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane12 = new javax.swing.JScrollPane();
        txtimpri = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                formVetoableChange(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("CLIENTE :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("DIRECCION :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 180, -1));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 180, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PASTILLA", "JARABES", "PERFUMERIA", "ACCESORIOS DE LIMPIEZA", " ", " " }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 130, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("TIPO DE PRODUCTO");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        listcolec.setBackground(new java.awt.Color(0, 153, 255));
        listcolec.setFont(new java.awt.Font("Tahoma", 1, 11));
        listcolec.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "PANADOL", "PARACETAMOL", "AMOCIXILINA", "APRONAX", "NAZTISOL", "PONSTAN", "REDOXON", "PEDIACHUR", " " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listcolec.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listcolecValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listcolec);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 140, 100));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Arial", 3, 14));
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 550, 110));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel4.setForeground(new java.awt.Color(255, 0, 51));
        jLabel4.setText("DESCRIPCION DEL PRODUCTO:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, -1, -1));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Arial", 1, 12));
        jButton2.setForeground(new java.awt.Color(255, 0, 51));
        jButton2.setText("NUEVO");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 640, 150, 30));

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Arial", 1, 12));
        jButton3.setForeground(new java.awt.Color(255, 0, 51));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/folder.sec.png"))); // NOI18N
        jButton3.setText("SALIR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 640, 150, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel6.setForeground(new java.awt.Color(51, 51, 255));
        jLabel6.setText("PRECIO TOTAL:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 330, -1, -1));
        jPanel1.add(txtpre, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 330, 130, -1));
        jPanel1.add(txtnro, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 130, 110, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel8.setForeground(new java.awt.Color(0, 0, 255));
        jLabel8.setText("NUMERO DE VENTA");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 140, -1, 10));

        listcolpre.setBackground(new java.awt.Color(0, 153, 255));
        listcolpre.setFont(new java.awt.Font("Tahoma", 1, 11));
        listcolpre.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "2.00", "1.50", "2.50", "1.50", "1.00", "1.50", "3.00", "1.00", " " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listcolpre.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listcolpreValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(listcolpre);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 60, 100));

        jList3.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList3ValueChanged(evt);
            }
        });
        jScrollPane4.setViewportView(jList3);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 250, 130, 140));

        jScrollPane5.setViewportView(jList4);

        jPanel1.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 250, 60, 140));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel13.setForeground(new java.awt.Color(0, 0, 255));
        jLabel13.setText("PRODUCTOS A LLEVAR ::");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 220, -1, -1));

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Arial", 1, 12));
        jButton4.setForeground(new java.awt.Color(0, 0, 255));
        jButton4.setText("AGREGAR");
        jButton4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, 90, 30));

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 11));
        jButton5.setForeground(new java.awt.Color(0, 0, 255));
        jButton5.setText("QUITAR");
        jButton5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 380, 90, 30));

        listcollar.setBackground(new java.awt.Color(0, 153, 255));
        listcollar.setFont(new java.awt.Font("Tahoma", 1, 11));
        listcollar.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "NAZTISOL", "PARACETAMOL", "VICKMIEL", "PALTOMIEL", " " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listcollar.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listcollarValueChanged(evt);
            }
        });
        jScrollPane6.setViewportView(listcollar);

        jPanel1.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 140, 100));

        listprecollar.setBackground(new java.awt.Color(0, 153, 255));
        listprecollar.setFont(new java.awt.Font("Tahoma", 1, 11));
        listprecollar.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "20.00", "33.50", "54.00", "32.00", " " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listprecollar.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listprecollarValueChanged(evt);
            }
        });
        jScrollPane7.setViewportView(listprecollar);

        jPanel1.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, 50, 100));

        listpendientes.setBackground(new java.awt.Color(0, 153, 255));
        listpendientes.setFont(new java.awt.Font("Tahoma", 1, 11));
        listpendientes.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "KALOS", "URBAN", "SALVAJE", "SPORT", "PULSO", "VANIDADES", " " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listpendientes.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listpendientesValueChanged(evt);
            }
        });
        jScrollPane8.setViewportView(listpendientes);

        jPanel1.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 140, 100));

        listprependi.setBackground(new java.awt.Color(0, 153, 255));
        listprependi.setFont(new java.awt.Font("Tahoma", 1, 11));
        listprependi.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "40.00", "50.00", "60.00", "55.00", "80.00", "92.50" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listprependi.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listprependiValueChanged(evt);
            }
        });
        jScrollPane9.setViewportView(listprependi);

        jPanel1.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 50, 100));

        listanillos.setBackground(new java.awt.Color(0, 153, 255));
        listanillos.setFont(new java.awt.Font("Tahoma", 1, 11));
        listanillos.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "KOLINOS", "JABON", "LISTERINE", "TALCOS", "SHAMPO", "CEPILLO", " " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listanillos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listanillosValueChanged(evt);
            }
        });
        jScrollPane10.setViewportView(listanillos);

        jPanel1.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 130, 100));

        listpreanillos.setBackground(new java.awt.Color(0, 153, 255));
        listpreanillos.setFont(new java.awt.Font("Tahoma", 1, 11));
        listpreanillos.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "9.00", "5.00", "7.50", "6.00", "2.00", "3.50", " " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listpreanillos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listpreanillosValueChanged(evt);
            }
        });
        jScrollPane11.setViewportView(listpreanillos);

        jPanel1.add(jScrollPane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 360, 60, 100));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel10.setForeground(new java.awt.Color(255, 0, 51));
        jLabel10.setText("PASTLLAS: ");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel15.setForeground(new java.awt.Color(255, 0, 51));
        jLabel15.setText("ACCESORIOS DE LIMPIEZA");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel16.setForeground(new java.awt.Color(255, 0, 51));
        jLabel16.setText("PERFUMES");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel17.setForeground(new java.awt.Color(255, 0, 51));
        jLabel17.setText("JARABES");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel18.setForeground(new java.awt.Color(0, 0, 255));
        jLabel18.setText("DNI :");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 110, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 36));
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoInkafarma.jpg"))); // NOI18N
        jLabel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 102), 5, true));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel19.setForeground(new java.awt.Color(0, 0, 255));
        jLabel19.setText("AV. AREQUIPA 1925   - LIMA");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel14.setForeground(new java.awt.Color(255, 0, 0));
        jLabel14.setText("FECHA :");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 60, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel21.setForeground(new java.awt.Color(255, 0, 0));
        jLabel21.setText("HORA :");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 90, -1, -1));

        lbldate.setFont(new java.awt.Font("Tahoma", 1, 11));
        lbldate.setForeground(new java.awt.Color(0, 0, 255));
        jPanel1.add(lbldate, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 40, 90, 10));

        lblhora.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblhora.setForeground(new java.awt.Color(0, 0, 255));
        jPanel1.add(lblhora, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 80, 90, 10));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("IMPRIMIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 640, 100, 30));

        li1.setForeground(new java.awt.Color(255, 255, 255));
        li1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MEDG0003g[1].jpg"))); // NOI18N
        jPanel1.add(li1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 430, 180, 180));

        li2.setForeground(new java.awt.Color(255, 255, 255));
        li2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paracetamol.jpg"))); // NOI18N
        jPanel1.add(li2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 420, 150, 210));

        li3.setForeground(new java.awt.Color(255, 255, 255));
        li3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Amoxicilina.jpg"))); // NOI18N
        jPanel1.add(li3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 460, 160, 130));

        li5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pas1.jpg"))); // NOI18N
        jPanel1.add(li5, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 420, 200, 200));

        li4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apronax[1].jpg"))); // NOI18N
        jPanel1.add(li4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 440, 150, 170));

        lj1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kolynos.jpg"))); // NOI18N
        jPanel1.add(lj1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 450, 190, 150));

        lj2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lim4.jpg"))); // NOI18N
        jPanel1.add(lj2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 440, 200, 190));

        lj3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lim1.jpg"))); // NOI18N
        jPanel1.add(lj3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 400, 180, 280));

        lj4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/talcoII_2[1].jpg"))); // NOI18N
        jPanel1.add(lj4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 430, 210, -1));

        lj5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shampoo.jpg"))); // NOI18N
        jPanel1.add(lj5, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 370, 290, 260));

        lk1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/KALOS.jpg"))); // NOI18N
        jPanel1.add(lk1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 390, 250, 250));

        lk2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/URBAN.jpg"))); // NOI18N
        jPanel1.add(lk2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 410, 200, 210));

        lk3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SALVAJE.jpg"))); // NOI18N
        jPanel1.add(lk3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 410, 220, 220));

        lk4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ESPORT.jpg"))); // NOI18N
        jPanel1.add(lk4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 420, 190, 220));

        lk5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PULSO.jpg"))); // NOI18N
        jPanel1.add(lk5, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 420, 190, 220));

        lm1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto-Flutox-jarabe200ml-big[1].jpg"))); // NOI18N
        jPanel1.add(lm1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 470, 150, 160));

        lm2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ja2.jpg"))); // NOI18N
        jPanel1.add(lm2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 430, 180, 210));

        lm3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prod-vick-miel.jpg"))); // NOI18N
        jPanel1.add(lm3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 490, 230, 160));
        jPanel1.add(lm4, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 420, 110, 250));

        lm5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ja1.jpg"))); // NOI18N
        jPanel1.add(lm5, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 430, 120, 250));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel11.setForeground(new java.awt.Color(255, 0, 51));
        jLabel11.setText("PASTLLAS: ");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel20.setForeground(new java.awt.Color(255, 0, 51));
        jLabel20.setText("ACCESORIOS DE LIMPIEZA");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel22.setForeground(new java.awt.Color(255, 0, 51));
        jLabel22.setText("PERFUMES");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel23.setForeground(new java.awt.Color(255, 0, 51));
        jLabel23.setText("JARABES");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel24.setForeground(new java.awt.Color(0, 0, 255));
        jLabel24.setText("DNI :");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        jTabbedPane1.addTab("NOTA DE VENTA", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtimpri.setColumns(20);
        txtimpri.setFont(new java.awt.Font("Courier New", 1, 12));
        txtimpri.setForeground(new java.awt.Color(0, 0, 255));
        txtimpri.setRows(5);
        jScrollPane12.setViewportView(txtimpri);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoInkafarma.jpg"))); // NOI18N
        jLabel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 51), 5, true));

        jButton6.setText("IMPRIMIR");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(380, 380, 380)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 677, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(276, 276, 276)
                        .addComponent(jLabel7)))
                .addContainerGap(242, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(189, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("IMPRIMIR NOTA DE NETA", jPanel2);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1020, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        int c;
        c = jComboBox1.getSelectedIndex();

        switch(c){
                    //visible
            case 0: 
                    this.listcolec.setVisible(true);
                    this.listcolpre.setVisible(true);
                    this.listcollar.setVisible(false);
                    this.listprecollar.setVisible(false);
                    this.listpendientes.setVisible(false);
                    this.listprependi.setVisible(false);
                    this.listanillos.setVisible(false);
                    this.listpreanillos.setVisible(false);

                   //limpiarindice
                    this.listcollar.clearSelection();
                    this.listprecollar.clearSelection();
                    this.listpendientes.clearSelection();
                    this.listprependi.clearSelection();
                    this.listanillos.clearSelection();
                    this.listpreanillos.clearSelection();
                    break;

            case 1:

                    
                    //visible
                    this.listcollar.setVisible(true);
                    this.listprecollar.setVisible(true);
                    this.listcolec.setVisible(false);
                    this.listcolpre.setVisible(false);
                    this.listpendientes.setVisible(false);
                    this.listprependi.setVisible(false);
                    this.listanillos.setVisible(false);
                    this.listpreanillos.setVisible(false);
                    //limpiar indice
                    this.listcolec.clearSelection();
                    this.listcolpre.clearSelection();
                    this.listpendientes.clearSelection();
                    this.listprependi.clearSelection();
                    this.listanillos.clearSelection();
                    this.listpreanillos.clearSelection();
                    break;
            
            case 2:
                    //visible
                    this.listpendientes.setVisible(true);
                    this.listprependi.setVisible(true);
                    this.listcollar.setVisible(false);
                    this.listprecollar.setVisible(false);
                    this.listcolec.setVisible(false);
                    this.listcolpre.setVisible(false);
                    this.listanillos.setVisible(false);
                    this.listpreanillos.setVisible(false);
                    //limpiar indice
                    this.listcollar.clearSelection();
                    this.listprecollar.clearSelection();
                    this.listcolec.clearSelection();
                    this.listcolpre.clearSelection();
                    this.listanillos.clearSelection();
                    this.listpreanillos.clearSelection();
                    break;

            case 3:
                //visible
                    this.listanillos.setVisible(true);
                    this.listpreanillos.setVisible(true);
                    this.listpendientes.setVisible(false);
                    this.listprependi.setVisible(false);
                    this.listcollar.setVisible(false);
                    this.listprecollar.setVisible(false);
                    this.listcolec.setVisible(false);
                    this.listcolpre.setVisible(false);
                  //limpiar indice
                     this.listpendientes.clearSelection();
                    this.listprependi.clearSelection();
                    this.listcollar.clearSelection();
                    this.listprecollar.clearSelection();
                    this.listcolec.clearSelection();
                    this.listcolpre.clearSelection();
                    break;

        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void listcolecValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listcolecValueChanged

     int indice;
      indice = listcolec.getSelectedIndex();
     listcolpre.setSelectedIndex(indice);
     jButton4.setEnabled(true);
    }//GEN-LAST:event_listcolecValueChanged

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int elegir;
        int  i;
        String procollar,coscollar;
        String propendi,cospendi;
        String proanillos,cosanillos;
        String producto,costo;
                double cuenta ,total = 0;
        elegir= jComboBox1.getSelectedIndex();
        switch(elegir){
            case 0:         
        //coleccion
       producto=(String)listcolec.getSelectedValue();
        costo=(String)listcolpre.getSelectedValue();
         //coleccion
        modelo1.addElement(producto);
        modelo2.addElement(costo);
      cuenta=modelo2.size();
        for(i=0;i<cuenta;i++)
              total = total+ Double.parseDouble((String)modelo2.elementAt(i));
       this.txtpre.setText(String.valueOf(total));
      if(i==6){
           
        }
     jButton4.setEnabled(false);
        break;

        //******************
            case 1:
         //collar
       procollar=(String)listcollar.getSelectedValue();
        coscollar=(String)listprecollar.getSelectedValue();
         //collar
        modelo1.addElement(procollar);
        modelo2.addElement(coscollar);
      cuenta=modelo2.size();
        for(i=0;i<cuenta;i++)
          total = total+ Double.parseDouble((String)modelo2.elementAt(i));
        this.txtpre.setText(String.valueOf(total));

           
        
        jButton4.setEnabled(false);
        break;

        //********************************
            case 2:
                //pendientes
       propendi=(String)listpendientes.getSelectedValue();
        cospendi=(String)listprependi.getSelectedValue();
         //pendientes
        modelo1.addElement(propendi);
        modelo2.addElement(cospendi);
      cuenta=modelo2.size();
        for(i=0;i<cuenta;i++)
            total = total+ Double.parseDouble((String)modelo2.elementAt(i));
        this.txtpre.setText(String.valueOf(total));
   
        jButton4.setEnabled(false);
        break;

        //************************************************
            case 3:
                   //anillos
       proanillos=(String)listanillos.getSelectedValue();
        cosanillos=(String)listpreanillos.getSelectedValue();
         //anillos
        modelo1.addElement(proanillos);
        modelo2.addElement(cosanillos);
      cuenta=modelo2.size();
        for(i=0;i<cuenta;i++)
            total = total+ Double.parseDouble((String)modelo2.elementAt(i));
        this.txtpre.setText(String.valueOf(total));
   
        jButton4.setEnabled(false);
        break;
                
        }


    }//GEN-LAST:event_jButton4ActionPerformed

    private void jList3ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList3ValueChanged
           int indice;
       indice = jList3.getSelectedIndex();
       jList4.setSelectedIndex(indice);
       jButton5.setEnabled(true);
    }//GEN-LAST:event_jList3ValueChanged

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
              int indice,i;
      double cuenta, total=0;
        indice = jList3.getSelectedIndex();
        modelo1.remove(indice);
        modelo2.remove(indice);
        cuenta = modelo2.size();
        for(i=0;i<cuenta;i++)
            total = total+ Double.parseDouble((String)modelo2.elementAt(i));
        txtpre.setText(String.valueOf(total));
        jButton5.setEnabled(false);

    }//GEN-LAST:event_jButton5ActionPerformed

    private void listcolpreValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listcolpreValueChanged
       int indice;

       indice = listcolpre.getSelectedIndex();
        switch(indice){
            case 0:
                this.jTextArea1.setText("");
                this.jTextArea1.setForeground(Color.BLUE);
                this.jTextArea1.append("PANADOL :" + "PASTILLAS PARA ALIVIAR CUALQUIER DOLOR DEL CUERPO \n DIFERNETE PRECIOS " + "\n");
                this.li1.setVisible(true);
                this.li2.setVisible(false);
                this.li3.setVisible(false);
                this.li4.setVisible(false);
                this.li5.setVisible(false);
                this.lj1.setVisible(false);
                this.lj2.setVisible(false);
                this.lj3.setVisible(false);
                this.lj4.setVisible(false);
                this.lj5.setVisible(false);
                this.lk1.setVisible(false);
                this.lk2.setVisible(false);
                this.lk3.setVisible(false);
                this.lk4.setVisible(false);
                this.lk5.setVisible(false);
                this.lm1.setVisible(false);
                this.lm2.setVisible(false);
                this.lm3.setVisible(false);
                this.lm4.setVisible(false);
                this.lm5.setVisible(false);

                break;
            case 1:
                this.jTextArea1.setText("");
                this.jTextArea1.setForeground(Color.BLUE);
                this.jTextArea1.append("PARACETAMOL:" + "PASTILLA QUE NOS ALIVIAR CUALQUIER DOLOR DE ESTOMAGO\n " + "\n");
                this.li1.setVisible(false);
                this.li2.setVisible(true);
                this.li3.setVisible(false);
                this.li4.setVisible(false);
                this.li5.setVisible(false);
                this.lj1.setVisible(false);
                this.lj2.setVisible(false);
                this.lj3.setVisible(false);
                this.lj4.setVisible(false);
                this.lj5.setVisible(false);
                this.lk1.setVisible(false);
                this.lk2.setVisible(false);
                this.lk3.setVisible(false);
                this.lk4.setVisible(false);
                this.lk5.setVisible(false);
                this.lm1.setVisible(false);
                this.lm2.setVisible(false);
                this.lm3.setVisible(false);
                this.lm4.setVisible(false);
                this.lm5.setVisible(false);
                break;
            case 2:
                this.jTextArea1.setText("");
                this.jTextArea1.setForeground(Color.BLUE);
                this.jTextArea1.append("AMOCIXILINA : PARA LA GRIPE Y DOLOR DE CABEZA" + " \n  2 TOMAS  " + "\n");
                this.li1.setVisible(false);
                this.li2.setVisible(false);
                this.li3.setVisible(true);
                this.li4.setVisible(false);
                this.li5.setVisible(false);
                this.lj1.setVisible(false);
                this.lj2.setVisible(false);
                this.lj3.setVisible(false);
                this.lj4.setVisible(false);
                this.lj5.setVisible(false);
                this.lk1.setVisible(false);
                this.lk2.setVisible(false);
                this.lk3.setVisible(false);
                this.lk4.setVisible(false);
                this.lk5.setVisible(false);
                this.lm1.setVisible(false);
                this.lm2.setVisible(false);
                this.lm3.setVisible(false);
                this.lm4.setVisible(false);
                this.lm5.setVisible(false);

                break;
            case 3:
                this.jTextArea1.setText("");
                this.jTextArea1.setForeground(Color.BLUE);
                this.jTextArea1.append("APRONAX: " + "PARA EL DOLOR MUSCULAR  " + "\n");
                this.li1.setVisible(false);
                this.li2.setVisible(false);
                this.li3.setVisible(false);
                this.li4.setVisible(true);
                this.li5.setVisible(false);
                this.lj1.setVisible(false);
                this.lj2.setVisible(false);
                this.lj3.setVisible(false);
                this.lj4.setVisible(false);
                this.lj5.setVisible(false);
                this.lk1.setVisible(false);
                this.lk2.setVisible(false);
                this.lk3.setVisible(false);
                this.lk4.setVisible(false);
                this.lk5.setVisible(false);
                this.lm1.setVisible(false);
                this.lm2.setVisible(false);
                this.lm3.setVisible(false);
                this.lm4.setVisible(false);
                this.lm5.setVisible(false);
                break;
            case 4:
                this.jTextArea1.setText("");
                this.jTextArea1.setForeground(Color.BLUE);
                this.jTextArea1.append("NAZTISOL :" + "ALIVIA LA FIEBRE \n CADA 8 HORAS" + "\n");
                this.li1.setVisible(false);
                this.li2.setVisible(false);
                this.li3.setVisible(false);
                this.li4.setVisible(false);
                this.li5.setVisible(true);
                this.lj1.setVisible(false);
                this.lj2.setVisible(false);
                this.lj3.setVisible(false);
                this.lj4.setVisible(false);
                this.lj5.setVisible(false);
                this.lk1.setVisible(false);
                this.lk2.setVisible(false);
                this.lk3.setVisible(false);
                this.lk4.setVisible(false);
                this.lk5.setVisible(false);
                this.lm1.setVisible(false);
                this.lm2.setVisible(false);
                this.lm3.setVisible(false);
                this.lm4.setVisible(false);
                this.lm5.setVisible(false);
                break;
            case 5:
                this.jTextArea1.setText("");
                this.jTextArea1.setForeground(Color.BLUE);
                this.jTextArea1.append("PONSTAN :" + "ALIVIA LOS COLOCOS MESTRUALES \n CADA 8 HORAS" + "\n");
                this.li1.setVisible(false);
                this.li2.setVisible(false);
                this.li3.setVisible(false);
                this.li4.setVisible(false);
                this.li5.setVisible(true);
                this.lj1.setVisible(false);
                this.lj2.setVisible(false);
                this.lj3.setVisible(false);
                this.lj4.setVisible(false);
                this.lj5.setVisible(false);
                this.lk1.setVisible(false);
                this.lk2.setVisible(false);
                this.lk3.setVisible(false);
                this.lk4.setVisible(false);
                this.lk5.setVisible(false);
                this.lm1.setVisible(false);
                this.lm2.setVisible(false);
                this.lm3.setVisible(false);
                this.lm4.setVisible(false);
                this.lm5.setVisible(false);
                break;
                            case 6:
                this.jTextArea1.setText("");
                this.jTextArea1.setForeground(Color.BLUE);
                this.jTextArea1.append("REDOXON :" + "ALIVIA LA FIEBRE \n CADA 8 HORAS" + "\n");
                this.li1.setVisible(false);
                this.li2.setVisible(false);
                this.li3.setVisible(false);
                this.li4.setVisible(false);
                this.li5.setVisible(true);
                this.lj1.setVisible(false);
                this.lj2.setVisible(false);
                this.lj3.setVisible(false);
                this.lj4.setVisible(false);
                this.lj5.setVisible(false);
                this.lk1.setVisible(false);
                this.lk2.setVisible(false);
                this.lk3.setVisible(false);
                this.lk4.setVisible(false);
                this.lk5.setVisible(false);
                this.lm1.setVisible(false);
                this.lm2.setVisible(false);
                this.lm3.setVisible(false);
                this.lm4.setVisible(false);
                this.lm5.setVisible(false);
                break;
                            case 7:
                this.jTextArea1.setText("");
                this.jTextArea1.setForeground(Color.BLUE);
                this.jTextArea1.append("PEDIACHUR :" + "PARA EL DOLOR DE LOS HUESOS EN ADULTOS \n CADA 8 HORAS" + "\n");
                this.li1.setVisible(false);
                this.li2.setVisible(false);
                this.li3.setVisible(false);
                this.li4.setVisible(false);
                this.li5.setVisible(true);
                this.lj1.setVisible(false);
                this.lj2.setVisible(false);
                this.lj3.setVisible(false);
                this.lj4.setVisible(false);
                this.lj5.setVisible(false);
                this.lk1.setVisible(false);
                this.lk2.setVisible(false);
                this.lk3.setVisible(false);
                this.lk4.setVisible(false);
                this.lk5.setVisible(false);
                this.lm1.setVisible(false);
                this.lm2.setVisible(false);
                this.lm3.setVisible(false);
                this.lm4.setVisible(false);
                this.lm5.setVisible(false);
                break;
                           

     }

    }//GEN-LAST:event_listcolpreValueChanged

    private void listcollarValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listcollarValueChanged
      int indice;
      indice = listcollar.getSelectedIndex();
     listprecollar.setSelectedIndex(indice);
     jButton4.setEnabled(true);
    }//GEN-LAST:event_listcollarValueChanged

    private void listprecollarValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listprecollarValueChanged

        int indice;

                indice = listprecollar.getSelectedIndex();
        switch(indice){
            case 0:
                this.jTextArea1.setText("");
                this.jTextArea1.setForeground(Color.blue);
                this.jTextArea1.append("NAZTISOL :" + "PARA EL DOLOR DE ESTOMAGO \n 250ML" + "\n");
                 this.lm1.setVisible(true);
                this.lm2.setVisible(false);
                this.lm3.setVisible(false);
                this.lm4.setVisible(false);
                this.lm5.setVisible(false);
                //**
                this.li1.setVisible(false);
                this.li2.setVisible(false);
                this.li3.setVisible(false);
                this.li4.setVisible(false);
                this.li5.setVisible(false);
                //**
                this.lj1.setVisible(false);
                this.lj2.setVisible(false);
                this.lj3.setVisible(false);
                this.lj4.setVisible(false);
                this.lj5.setVisible(false);
                //**
                this.lk1.setVisible(false);
                this.lk2.setVisible(false);
                this.lk3.setVisible(false);
                this.lk4.setVisible(false);
                this.lk5.setVisible(false);
                break;
            case 1:
                this.jTextArea1.setText("");
                this.jTextArea1.setForeground(Color.blue);
                this.jTextArea1.append("PARACETAMOL:" + "PARA EL DOLOR DE STOMAGO \n INCLUYE CUCHARITA " + "\n");
                this.lm1.setVisible(false);
                this.lm2.setVisible(true);
                this.lm3.setVisible(false);
                this.lm4.setVisible(false);
                this.lm5.setVisible(false);
                //**
                this.li1.setVisible(false);
                this.li2.setVisible(false);
                this.li3.setVisible(false);
                this.li4.setVisible(false);
                this.li5.setVisible(false);
                //**
                this.lj1.setVisible(false);
                this.lj2.setVisible(false);
                this.lj3.setVisible(false);
                this.lj4.setVisible(false);
                this.lj5.setVisible(false);
                //**
                this.lk1.setVisible(false);
                this.lk2.setVisible(false);
                this.lk3.setVisible(false);
                this.lk4.setVisible(false);
                this.lk5.setVisible(false);
                break;
            case 2:
                this.jTextArea1.setText("");
                this.jTextArea1.setForeground(Color.blue);
                this.jTextArea1.append("VICKMIEL :" + "ALIVIA LA GRIPE Y TOS SECA " + "\n");
              this.lm1.setVisible(false);
                this.lm2.setVisible(false);
                this.lm3.setVisible(true);
                this.lm4.setVisible(false);
                this.lm5.setVisible(false);
                //**
                this.li1.setVisible(false);
                this.li2.setVisible(false);
                this.li3.setVisible(false);
                this.li4.setVisible(false);
                this.li5.setVisible(false);
                //**
                this.lj1.setVisible(false);
                this.lj2.setVisible(false);
                this.lj3.setVisible(false);
                this.lj4.setVisible(false);
                this.lj5.setVisible(false);
                //**
                this.lk1.setVisible(false);
                this.lk2.setVisible(false);
                this.lk3.setVisible(false);
                this.lk4.setVisible(false);
                this.lk5.setVisible(false);
                break;
            case 3:
                this.jTextArea1.setText("");
                this.jTextArea1.setForeground(Color.blue);
                this.jTextArea1.append("PALTOMIEL: " + "ALIVIA LA TOS SECA \n 2 VECES AL DIA " + "\n");
                this.lm1.setVisible(false);
                this.lm2.setVisible(false);
                this.lm3.setVisible(false);
                this.lm4.setVisible(true);
                this.lm5.setVisible(false);
                //**
                this.li1.setVisible(false);
                this.li2.setVisible(false);
                this.li3.setVisible(false);
                this.li4.setVisible(false);
                this.li5.setVisible(false);
                //**
                this.lj1.setVisible(false);
                this.lj2.setVisible(false);
                this.lj3.setVisible(false);
                this.lj4.setVisible(false);
                this.lj5.setVisible(false);
                //**
                this.lk1.setVisible(false);
                this.lk2.setVisible(false);
                this.lk3.setVisible(false);
                this.lk4.setVisible(false);
                this.lk5.setVisible(false);
                break;
           

     }
    }//GEN-LAST:event_listprecollarValueChanged

    private void listpendientesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listpendientesValueChanged
        int indice;
      indice = listpendientes.getSelectedIndex();
     listprependi.setSelectedIndex(indice);
     jButton4.setEnabled(true);
    }//GEN-LAST:event_listpendientesValueChanged

    private void listprependiValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listprependiValueChanged

        int indice;
       indice = listprependi.getSelectedIndex();
        switch(indice){
            case 0:
                this.jTextArea1.setText("");
                this.jTextArea1.setForeground(Color.magenta);
                this.jTextArea1.append("KALOS :" + "PERFUME PARA VARON 100% ELEGANTE " + "\n");
                 this.lk1.setVisible(true);
                this.lk2.setVisible(false);
                this.lk3.setVisible(false);
                this.lk4.setVisible(false);
                this.lk5.setVisible(false);
                //**
                this.li1.setVisible(false);
                this.li2.setVisible(false);
                this.li3.setVisible(false);
                this.li4.setVisible(false);
                this.li5.setVisible(false);
                //**
                this.lj1.setVisible(false);
                this.lj2.setVisible(false);
                this.lj3.setVisible(false);
                this.lj4.setVisible(false);
                this.lj5.setVisible(false);
                //**
                this.lm1.setVisible(false);
                this.lm2.setVisible(false);
                this.lm3.setVisible(false);
                this.lm4.setVisible(false);
                this.lm5.setVisible(false);
                break;
            case 1:
                this.jTextArea1.setText("");
                this.jTextArea1.setForeground(Color.magenta);
                this.jTextArea1.append("URBAN :" + "PERFUME CASUAL " + "\n");
               this.lk1.setVisible(false);
                this.lk2.setVisible(true);
                this.lk3.setVisible(false);
                this.lk4.setVisible(false);
                this.lk5.setVisible(false);
                //**
                this.li1.setVisible(false);
                this.li2.setVisible(false);
                this.li3.setVisible(false);
                this.li4.setVisible(false);
                this.li5.setVisible(false);
                //**
                this.lj1.setVisible(false);
                this.lj2.setVisible(false);
                this.lj3.setVisible(false);
                this.lj4.setVisible(false);
                this.lj5.setVisible(false);
                //**
                this.lm1.setVisible(false);
                this.lm2.setVisible(false);
                this.lm3.setVisible(false);
                this.lm4.setVisible(false);
                this.lm5.setVisible(false);
                break;
            case 2:
                this.jTextArea1.setText("");
                this.jTextArea1.setForeground(Color.magenta);
                this.jTextArea1.append("SALVAJE :" + "FRAGANCIA VARONIL  " + "\n");
                this.lk1.setVisible(false);
                this.lk2.setVisible(false);
                this.lk3.setVisible(true);
                this.lk4.setVisible(false);
                this.lk5.setVisible(false);
                //**
                this.li1.setVisible(false);
                this.li2.setVisible(false);
                this.li3.setVisible(false);
                this.li4.setVisible(false);
                this.li5.setVisible(false);
                //**
                this.lj1.setVisible(false);
                this.lj2.setVisible(false);
                this.lj3.setVisible(false);
                this.lj4.setVisible(false);
                this.lj5.setVisible(false);
                //**
                this.lm1.setVisible(false);
                this.lm2.setVisible(false);
                this.lm3.setVisible(false);
                this.lm4.setVisible(false);
                this.lm5.setVisible(false);
                break;
            case 3:
                this.jTextArea1.setText("");
                this.jTextArea1.setForeground(Color.magenta);
                this.jTextArea1.append("SPORT : " + "PERFUME PARA CUALQUIER OCACION \n 10% MAS  " + "\n");
                this.lk1.setVisible(false);
                this.lk2.setVisible(false);
                this.lk3.setVisible(false);
                this.lk4.setVisible(true);
                this.lk5.setVisible(false);
                //**
                this.li1.setVisible(false);
                this.li2.setVisible(false);
                this.li3.setVisible(false);
                this.li4.setVisible(false);
                this.li5.setVisible(false);
                //**
                this.lj1.setVisible(false);
                this.lj2.setVisible(false);
                this.lj3.setVisible(false);
                this.lj4.setVisible(false);
                this.lj5.setVisible(false);
                //**
                this.lm1.setVisible(false);
                this.lm2.setVisible(false);
                this.lm3.setVisible(false);
                this.lm4.setVisible(false);
                this.lm5.setVisible(false);
                break;
            case 4:
                this.jTextArea1.setText("");
                this.jTextArea1.setForeground(Color.magenta);
                this.jTextArea1.append(" PULSO:" + "FRGANCIA QUE ENCANTA A LAS DAMAS \n " + "\n");
                this.lk1.setVisible(false);
                this.lk2.setVisible(false);
                this.lk3.setVisible(false);
                this.lk4.setVisible(false);
                this.lk5.setVisible(true);
                //**
                this.li1.setVisible(false);
                this.li2.setVisible(false);
                this.li3.setVisible(false);
                this.li4.setVisible(false);
                this.li5.setVisible(false);
                //**
                this.lj1.setVisible(false);
                this.lj2.setVisible(false);
                this.lj3.setVisible(false);
                this.lj4.setVisible(false);
                this.lj5.setVisible(false);
                //**
                this.lm1.setVisible(false);
                this.lm2.setVisible(false);
                this.lm3.setVisible(false);
                this.lm4.setVisible(false);
                this.lm5.setVisible(false);
                break;
            case 5:
                this.jTextArea1.setText("");
                this.jTextArea1.setForeground(Color.magenta);
                this.jTextArea1.append("VANIDADES:" + "PERFUME DE GRAN CALIDAD Y ELAGACIA \n " + "\n");
                this.lk1.setVisible(false);
                this.lk2.setVisible(false);
                this.lk3.setVisible(false);
                this.lk4.setVisible(false);
                this.lk5.setVisible(true);
                //**
                this.li1.setVisible(false);
                this.li2.setVisible(false);
                this.li3.setVisible(false);
                this.li4.setVisible(false);
                this.li5.setVisible(false);
                //**
                this.lj1.setVisible(false);
                this.lj2.setVisible(false);
                this.lj3.setVisible(false);
                this.lj4.setVisible(false);
                this.lj5.setVisible(false);
                //**
                this.lm1.setVisible(false);
                this.lm2.setVisible(false);
                this.lm3.setVisible(false);
                this.lm4.setVisible(false);
                this.lm5.setVisible(false);
                break;

     }
    }//GEN-LAST:event_listprependiValueChanged

    private void listanillosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listanillosValueChanged
       int indice;
      indice = listanillos.getSelectedIndex();
     listpreanillos.setSelectedIndex(indice);
     jButton4.setEnabled(true);
    }//GEN-LAST:event_listanillosValueChanged

    private void listpreanillosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listpreanillosValueChanged
         int indice;
       indice = listpreanillos.getSelectedIndex();
        switch(indice){
            case 0:
                this.jTextArea1.setText("");
                this.jTextArea1.setForeground(Color.BLUE);
                this.jTextArea1.append("KOLINOS :" + "DEJA LOS DIENTES TOTALMENTE LIMPIOS Y GRAN FRESCURA " + "\n");
                 this.lj1.setVisible(true);
                this.lj2.setVisible(false);
                this.lj3.setVisible(false);
                this.lj4.setVisible(false);
                this.lj5.setVisible(false);
                //**
                this.li1.setVisible(false);
                this.li2.setVisible(false);
                this.li3.setVisible(false);
                this.li4.setVisible(false);
                this.li5.setVisible(false);
                //**
                this.lk1.setVisible(false);
                this.lk2.setVisible(false);
                this.lk3.setVisible(false);
                this.lk4.setVisible(false);
                this.lk5.setVisible(false);
                //**
                this.lm1.setVisible(false);
                this.lm2.setVisible(false);
                this.lm3.setVisible(false);
                this.lm4.setVisible(false);
                this.lm5.setVisible(false);
                break;
            case 1:
                this.jTextArea1.setText("");
                this.jTextArea1.setForeground(Color.BLUE);
                this.jTextArea1.append("JABON :" + " TIENE GRAN OLOR 100% ANTIBACTERIANO" + "\n");
                 this.lj1.setVisible(false);
                this.lj2.setVisible(true);
                this.lj3.setVisible(false);
                this.lj4.setVisible(false);
                this.lj5.setVisible(false);
                //**
                this.li1.setVisible(false);
                this.li2.setVisible(false);
                this.li3.setVisible(false);
                this.li4.setVisible(false);
                this.li5.setVisible(false);
                //**
                this.lk1.setVisible(false);
                this.lk2.setVisible(false);
                this.lk3.setVisible(false);
                this.lk4.setVisible(false);
                this.lk5.setVisible(false);
                //**
                this.lm1.setVisible(false);
                this.lm2.setVisible(false);
                this.lm3.setVisible(false);
                this.lm4.setVisible(false);
                this.lm5.setVisible(false);


                break;
            case 2:
                this.jTextArea1.setText("");
                this.jTextArea1.setForeground(Color.BLUE);
                this.jTextArea1.append("LISTERINE :" + "TE DEJA LOS DIENTES TOTAMENTE BLANCOS" + "\n");
                 this.lj1.setVisible(false);
                this.lj2.setVisible(false);
                this.lj3.setVisible(true);
                this.lj4.setVisible(false);
                this.lj5.setVisible(false);
                //**
                this.li1.setVisible(false);
                this.li2.setVisible(false);
                this.li3.setVisible(false);
                this.li4.setVisible(false);
                this.li5.setVisible(false);
                //**
                this.lk1.setVisible(false);
                this.lk2.setVisible(false);
                this.lk3.setVisible(false);
                this.lk4.setVisible(false);
                this.lk5.setVisible(false);
                //**
                this.lm1.setVisible(false);
                this.lm2.setVisible(false);
                this.lm3.setVisible(false);
                this.lm4.setVisible(false);
                this.lm5.setVisible(false);
                break;
            case 3:
                this.jTextArea1.setText("");
                this.jTextArea1.setForeground(Color.BLUE);
                this.jTextArea1.append("TALCOS :" + "TE DA UNA GRAN SUAVIDAS Y AROMA A LA PIEL" + "\n");
                this.lj1.setVisible(false);
                this.lj2.setVisible(false);
                this.lj3.setVisible(false);
                this.lj4.setVisible(true);
                this.lj5.setVisible(false);
                //**
                this.li1.setVisible(false);
                this.li2.setVisible(false);
                this.li3.setVisible(false);
                this.li4.setVisible(false);
                this.li5.setVisible(false);
                //**
                this.lk1.setVisible(false);
                this.lk2.setVisible(false);
                this.lk3.setVisible(false);
                this.lk4.setVisible(false);
                this.lk5.setVisible(false);
                //**
                this.lm1.setVisible(false);
                this.lm2.setVisible(false);
                this.lm3.setVisible(false);
                this.lm4.setVisible(false);
                this.lm5.setVisible(false);
                break;
            case 4:
                this.jTextArea1.setText("");
                this.jTextArea1.setForeground(Color.BLUE);
                this.jTextArea1.append("SHAMPO :" + "TE DEJA EL CABELLO TOTALMENTE SUAVE" + "\n");
                this.lj1.setVisible(false);
                this.lj2.setVisible(false);
                this.lj3.setVisible(false);
                this.lj4.setVisible(false);
                this.lj5.setVisible(true);
                //**
                this.li1.setVisible(false);
                this.li2.setVisible(false);
                this.li3.setVisible(false);
                this.li4.setVisible(false);
                this.li5.setVisible(false);
                //**
                this.lk1.setVisible(false);
                this.lk2.setVisible(false);
                this.lk3.setVisible(false);
                this.lk4.setVisible(false);
                this.lk5.setVisible(false);
                //**
                this.lm1.setVisible(false);
                this.lm2.setVisible(false);
                this.lm3.setVisible(false);
                this.lm4.setVisible(false);
                this.lm5.setVisible(false);
                break;
            case 5:
                this.jTextArea1.setText("");
                this.jTextArea1.setForeground(Color.BLUE);
                this.jTextArea1.append("CEPILLO :" + "CEPILLO DE HILOS FLEXIBLES QUE TE DAN MEJOR CEPILLADO" + "\n");
                this.lj1.setVisible(false);
                this.lj2.setVisible(false);
                this.lj3.setVisible(false);
                this.lj4.setVisible(false);
                this.lj5.setVisible(true);
                //**
                this.li1.setVisible(false);
                this.li2.setVisible(false);
                this.li3.setVisible(false);
                this.li4.setVisible(false);
                this.li5.setVisible(false);
                //**
                this.lk1.setVisible(false);
                this.lk2.setVisible(false);
                this.lk3.setVisible(false);
                this.lk4.setVisible(false);
                this.lk5.setVisible(false);
                //**
                this.lm1.setVisible(false);
                this.lm2.setVisible(false);
                this.lm3.setVisible(false);
                this.lm4.setVisible(false);
                this.lm5.setVisible(false);
                break;
        }
    }//GEN-LAST:event_listpreanillosValueChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.jTextField1.setText("");
        this.jTextField2.setText("");
        this.jTextField3.setText("");
        this.txtnro.setText("");
        this.txtpre.setText("");
        this.jTextArea1.setText("");
        this.jComboBox1.setSelectedIndex(-1);
        this.listcolec.setVisible(false);
        this.listcolpre.setVisible(false);
        this.listcollar.setVisible(false);
        this.listprecollar.setVisible(false);
        this.listpendientes.setVisible(false);
        this.listprependi.setVisible(false);
        this.listanillos.setVisible(false);
        this.listpreanillos.setVisible(false);
        this.modelo1.clear();
        this.modelo2.clear();
        this.listcolec.clearSelection();
        this.listcolpre.clearSelection();
        this.listcollar.clearSelection();
        this.listprecollar.clearSelection();
        this.listpendientes.clearSelection();
        this.listprependi.clearSelection();
        this.listanillos.clearSelection();
        this.listpreanillos.clearSelection();
        this.jButton4.setEnabled(false);
        this.jButton5.setEnabled(false);
          //limpiar imagenes
                this.lj1.setVisible(false);
                this.lj2.setVisible(false);
                this.lj3.setVisible(false);
                this.lj4.setVisible(false);
                this.lj5.setVisible(false);
                //**
                this.li1.setVisible(false);
                this.li2.setVisible(false);
                this.li3.setVisible(false);
                this.li4.setVisible(false);
                this.li5.setVisible(false);
                //**
                this.lk1.setVisible(false);
                this.lk2.setVisible(false);
                this.lk3.setVisible(false);
                this.lk4.setVisible(false);
                this.lk5.setVisible(false);
                //**
                this.lm1.setVisible(false);
                this.lm2.setVisible(false);
                this.lm3.setVisible(false);
                this.lm4.setVisible(false);
                this.lm5.setVisible(false);


        //contador
        cont = cont +1;
        txtnro.setText("00"+cont);
        JOptionPane.showMessageDialog(null,"NUEVA FACTURA" +"\n");
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_formVetoableChange
      Calendar cal= Calendar.getInstance();

 String fecha= cal.get(cal.DATE)+"/"+cal.get(cal.MONTH)+"/"+cal.get(cal.YEAR);
String hora= cal.get(cal.HOUR_OF_DAY)+":"+cal.get(cal.MINUTE)+":"+cal.get(cal.SECOND);
      lbldate.setText(""+fecha);
      lblhora.setText(""+hora);

        // TODO add your handling code here:
    }//GEN-LAST:event_formVetoableChange

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    nombreemp=("   "+'\t'+'\t'+'\t'+'\t'+"FARMACIA ---InkaFarma---");
    numfac=txtnro.getText();
    nombrecliente=jTextField1.getText();
    dire=jTextField2.getText();
    ndni=jTextField3.getText();
    JOptionPane.showMessageDialog(null, "RECUERDE QUE UNA VEZ PRESIONADO EL BOTON DE COMPRA"+'\n'+"SU ORDEN SERA PROCESADA E IRREVOCABLE","FARMACIA -InkaFarma-",JOptionPane.INFORMATION_MESSAGE);
encabezado=("     PRECIO TOTAL"+'\n');
txtimpri.setText(nombreemp+'\t'+'\t'+'\t'+'\t'+'\t'+'\n'+"Nª DE FACTURA :   "+numfac+'\n'+'\n'+"NOMBRE DE CLIENTE :   "+nombrecliente+'\n'+'\n'+"DIRECCION :   "+dire+'\n'+'\n'+"Nª DE DNI  :   "+ndni+'\n'+'\n'+'\n'+'\n'+encabezado+'\n');
        String mostrar1="";


preciou=txtpre.getText();

mostrar1+=('\t'+'\t'+preciou);

txtimpri.setText(txtimpri.getText()+mostrar1);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
chooser=new JFileChooser();
int seleccion;
FileWriter escribir;
BufferedWriter hacer;
String nombrearchivo,texto;
JOptionPane.showMessageDialog(null, "RECUERDE ESCRIBIR EL DOC. DESPUES DEL NOMBRE DE SU ARCHIVO","InkaFarma",JOptionPane.INFORMATION_MESSAGE);
seleccion=chooser.showSaveDialog(this);
chooser.setApproveButtonText("GUARDAR");
if(seleccion==chooser.APPROVE_OPTION){
    try{
    nombrearchivo=chooser.getSelectedFile().getAbsolutePath();
    texto=txtimpri.getText();
    escribir=new FileWriter(nombrearchivo);
    hacer=new BufferedWriter(escribir);
    hacer.write(texto);
    hacer.close();
    }catch(IOException ex){
        JOptionPane.showMessageDialog(null,"GRACIAS POR SU COMPRA","InkaFarma", JOptionPane.INFORMATION_MESSAGE);
        this.dispose();
    }


}

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser chooser;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList jList3;
    private javax.swing.JList jList4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel lbldate;
    private javax.swing.JLabel lblhora;
    private javax.swing.JLabel li1;
    private javax.swing.JLabel li2;
    private javax.swing.JLabel li3;
    private javax.swing.JLabel li4;
    private javax.swing.JLabel li5;
    private javax.swing.JList listanillos;
    private javax.swing.JList listcolec;
    private javax.swing.JList listcollar;
    private javax.swing.JList listcolpre;
    private javax.swing.JList listpendientes;
    private javax.swing.JList listpreanillos;
    private javax.swing.JList listprecollar;
    private javax.swing.JList listprependi;
    private javax.swing.JLabel lj1;
    private javax.swing.JLabel lj2;
    private javax.swing.JLabel lj3;
    private javax.swing.JLabel lj4;
    private javax.swing.JLabel lj5;
    private javax.swing.JLabel lk1;
    private javax.swing.JLabel lk2;
    private javax.swing.JLabel lk3;
    private javax.swing.JLabel lk4;
    private javax.swing.JLabel lk5;
    private javax.swing.JLabel lm1;
    private javax.swing.JLabel lm2;
    private javax.swing.JLabel lm3;
    private javax.swing.JLabel lm4;
    private javax.swing.JLabel lm5;
    private javax.swing.JTextArea txtimpri;
    private javax.swing.JTextField txtnro;
    private javax.swing.JTextField txtpre;
    // End of variables declaration//GEN-END:variables

}
