/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * accesorios.java
 *
 * Created on 17/03/2011, 02:03:46 PM
 */

/**
 *
 * @author alumno
 */
import java.awt.Color;
import javax.swing.*;
public class VER_PRODUCTOS extends javax.swing.JInternalFrame {

    int cont;
    private DefaultListModel modelo1= new DefaultListModel();
    private DefaultListModel modelo2= new DefaultListModel();

    /** Creates new form accesorios */
    public VER_PRODUCTOS() {
        initComponents();

        this.jComboBox1.setSelectedIndex(-1);

        this.listcolec.setVisible(false);
        this.listcolpre.setVisible(false);
        this.listcollar.setVisible(false);
        this.listprecollar.setVisible(false);
        this.listpendientes.setVisible(false);
        this.listprependi.setVisible(false);
        this.listanillos.setVisible(false);
        this.listpreanillos.setVisible(false);
        
        //imagenes
        this.li1.setVisible(false);
        this.li2.setVisible(false);
        this.li3.setVisible(false);
        this.li4.setVisible(false);
        this.li5.setVisible(false);
        this.lj1.setVisible(false);
        this.lj2.setVisible(false);
        this.lj3.setVisible(false);
        this.lj4.setVisible(false);
        this.lj5.setVisible(false);
        this.lk1.setVisible(false);
        this.lk2.setVisible(false);
        this.lk3.setVisible(false);
        this.lk4.setVisible(false);
        this.lk5.setVisible(false);
        this.lm1.setVisible(false);
        this.lm2.setVisible(false);
        this.lm3.setVisible(false);
        this.lm4.setVisible(false);
        this.lm5.setVisible(false);



        //contador
 JOptionPane.showMessageDialog(null,"-- VER PRODUCTOS --" +"\n");
        
         
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listcolec = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listcolpre = new javax.swing.JList();
        jScrollPane6 = new javax.swing.JScrollPane();
        listcollar = new javax.swing.JList();
        jScrollPane7 = new javax.swing.JScrollPane();
        listprecollar = new javax.swing.JList();
        jScrollPane8 = new javax.swing.JScrollPane();
        listpendientes = new javax.swing.JList();
        jScrollPane9 = new javax.swing.JScrollPane();
        listprependi = new javax.swing.JList();
        jScrollPane10 = new javax.swing.JScrollPane();
        listanillos = new javax.swing.JList();
        jScrollPane11 = new javax.swing.JScrollPane();
        listpreanillos = new javax.swing.JList();
        jLabel10 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        li1 = new javax.swing.JLabel();
        li2 = new javax.swing.JLabel();
        li3 = new javax.swing.JLabel();
        li5 = new javax.swing.JLabel();
        li4 = new javax.swing.JLabel();
        lj1 = new javax.swing.JLabel();
        lj2 = new javax.swing.JLabel();
        lj3 = new javax.swing.JLabel();
        lj4 = new javax.swing.JLabel();
        lj5 = new javax.swing.JLabel();
        lk1 = new javax.swing.JLabel();
        lk2 = new javax.swing.JLabel();
        lk3 = new javax.swing.JLabel();
        lk4 = new javax.swing.JLabel();
        lk5 = new javax.swing.JLabel();
        lm1 = new javax.swing.JLabel();
        lm2 = new javax.swing.JLabel();
        lm3 = new javax.swing.JLabel();
        lm4 = new javax.swing.JLabel();
        lm5 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setFont(new java.awt.Font("Courier New", 1, 11));
        jComboBox1.setForeground(new java.awt.Color(0, 0, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PASTILLA", "JARABES", "PERFUMERIA", "ACCESORIOS DE LIMPIEZA", " ", " " }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 130, -1));

        jLabel3.setFont(new java.awt.Font("Courier New", 1, 12));
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("TIPO DE PRODUCTO");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        listcolec.setBackground(new java.awt.Color(0, 153, 255));
        listcolec.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        listcolec.setFont(new java.awt.Font("Tahoma", 1, 11));
        listcolec.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "PANADOL", "PARACETAMOL", "AMOCIXILINA", "APRONAX", "NAZTISOL", "PONSTAN", "REDOXON", "PEDIACHUR", " " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listcolec.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listcolecValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listcolec);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 160, 100));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Arial", 3, 14));
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 580, 70));

        jLabel4.setFont(new java.awt.Font("Courier New", 1, 12));
        jLabel4.setForeground(new java.awt.Color(255, 0, 51));
        jLabel4.setText("DESCRIPCION DEL PRODUCTO:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, -1, -1));

        listcolpre.setBackground(new java.awt.Color(0, 153, 255));
        listcolpre.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        listcolpre.setFont(new java.awt.Font("Tahoma", 1, 11));
        listcolpre.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "2.00", "1.50", "2.50", "1.50", "1.00", "1.50", "3.00", "1.00", " " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listcolpre.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listcolpreValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(listcolpre);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 60, 100));

        listcollar.setBackground(new java.awt.Color(0, 153, 255));
        listcollar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        listcollar.setFont(new java.awt.Font("Tahoma", 1, 11));
        listcollar.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "NAZTISOL", "PARACETAMOL", "VICKMIEL", "PALTOMIEL", " " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listcollar.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listcollarValueChanged(evt);
            }
        });
        jScrollPane6.setViewportView(listcollar);

        jPanel1.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 130, 100));

        listprecollar.setBackground(new java.awt.Color(0, 153, 255));
        listprecollar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        listprecollar.setFont(new java.awt.Font("Tahoma", 1, 11));
        listprecollar.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "20.00", "33.50", "54.00", "32.00", " " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listprecollar.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listprecollarValueChanged(evt);
            }
        });
        jScrollPane7.setViewportView(listprecollar);

        jPanel1.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 50, 100));

        listpendientes.setBackground(new java.awt.Color(0, 153, 255));
        listpendientes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        listpendientes.setFont(new java.awt.Font("Tahoma", 1, 11));
        listpendientes.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "KALOS", "URBAN", "SALVAJE", "SPORT", "PULSO", "VANIDADES", " " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listpendientes.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listpendientesValueChanged(evt);
            }
        });
        jScrollPane8.setViewportView(listpendientes);

        jPanel1.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 160, 100));

        listprependi.setBackground(new java.awt.Color(0, 153, 255));
        listprependi.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        listprependi.setFont(new java.awt.Font("Tahoma", 1, 11));
        listprependi.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "40.00", "50.00", "60.00", "55.00", "80.00", "92.50" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listprependi.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listprependiValueChanged(evt);
            }
        });
        jScrollPane9.setViewportView(listprependi);

        jPanel1.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 60, 100));

        listanillos.setBackground(new java.awt.Color(0, 153, 255));
        listanillos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        listanillos.setFont(new java.awt.Font("Tahoma", 1, 11));
        listanillos.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "KOLINOS", "JABON", "LISTERINE", "TALCOS", "SHAMPO", "CEPILLO", " " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listanillos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listanillosValueChanged(evt);
            }
        });
        jScrollPane10.setViewportView(listanillos);

        jPanel1.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, 120, 100));

        listpreanillos.setBackground(new java.awt.Color(0, 153, 255));
        listpreanillos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        listpreanillos.setFont(new java.awt.Font("Tahoma", 1, 11));
        listpreanillos.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "9.00", "5.00", "7.50", "6.00", "2.00", "3.50", " " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listpreanillos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listpreanillosValueChanged(evt);
            }
        });
        jScrollPane11.setViewportView(listpreanillos);

        jPanel1.add(jScrollPane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 340, 60, 100));

        jLabel10.setFont(new java.awt.Font("Courier New", 1, 12));
        jLabel10.setForeground(new java.awt.Color(255, 0, 51));
        jLabel10.setText("PASTLLAS: ");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel15.setFont(new java.awt.Font("Courier New", 1, 12));
        jLabel15.setForeground(new java.awt.Color(255, 0, 51));
        jLabel15.setText("ACCESORIOS DE LIMPIEZA");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, -1, -1));

        jLabel16.setFont(new java.awt.Font("Courier New", 1, 12));
        jLabel16.setForeground(new java.awt.Color(255, 0, 51));
        jLabel16.setText("PERFUMES");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        jLabel17.setFont(new java.awt.Font("Courier New", 1, 12));
        jLabel17.setForeground(new java.awt.Color(255, 0, 51));
        jLabel17.setText("JARABES");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, -1, -1));

        jLabel5.setFont(new java.awt.Font("Courier New", 1, 36));
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("NUESTROS PRODUCTOS");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, -1, -1));

        jLabel19.setFont(new java.awt.Font("Courier New", 1, 12));
        jLabel19.setForeground(new java.awt.Color(0, 0, 255));
        jLabel19.setText("AV. AREQUIPA 1925   - LIMA");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medico-04.gif"))); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 0, 120, 170));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Courier New", 1, 12));
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("IMAGEN DE PRODUCTO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 150, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/INKA FARMA.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 240, 140));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Courier New", 1, 14));
        jButton1.setForeground(new java.awt.Color(0, 0, 255));
        jButton1.setText("SALIR");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 573, 90, 40));

        li1.setForeground(new java.awt.Color(255, 255, 255));
        li1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MEDG0003g[1].jpg"))); // NOI18N
        jPanel1.add(li1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 250, 180, 180));

        li2.setForeground(new java.awt.Color(255, 255, 255));
        li2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paracetamol.jpg"))); // NOI18N
        jPanel1.add(li2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 200, 150, 210));

        li3.setForeground(new java.awt.Color(255, 255, 255));
        li3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Amoxicilina.jpg"))); // NOI18N
        jPanel1.add(li3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 280, 160, 130));

        li5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pas1.jpg"))); // NOI18N
        jPanel1.add(li5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 230, 200, 200));

        li4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apronax[1].jpg"))); // NOI18N
        jPanel1.add(li4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 190, 150, 170));

        lj1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kolynos.jpg"))); // NOI18N
        jPanel1.add(lj1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 280, 190, 150));

        lj2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lim4.jpg"))); // NOI18N
        jPanel1.add(lj2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 190, 200, 190));

        lj3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lim1.jpg"))); // NOI18N
        jPanel1.add(lj3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 160, 180, 280));

        lj4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/talcoII_2[1].jpg"))); // NOI18N
        jPanel1.add(lj4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 240, 210, -1));

        lj5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shampoo.jpg"))); // NOI18N
        jPanel1.add(lj5, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 180, 290, 260));

        lk1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/KALOS.jpg"))); // NOI18N
        jPanel1.add(lk1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 190, 250, 250));

        lk2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/URBAN.jpg"))); // NOI18N
        jPanel1.add(lk2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 210, 200, 210));

        lk3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SALVAJE.jpg"))); // NOI18N
        jPanel1.add(lk3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 210, 220, 220));

        lk4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ESPORT.jpg"))); // NOI18N
        jPanel1.add(lk4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 170, 190, 220));

        lk5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PULSO.jpg"))); // NOI18N
        jPanel1.add(lk5, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 210, 190, 220));

        lm1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto-Flutox-jarabe200ml-big[1].jpg"))); // NOI18N
        jPanel1.add(lm1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 240, 150, 170));

        lm2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ja2.jpg"))); // NOI18N
        jPanel1.add(lm2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 220, 180, 210));

        lm3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prod-vick-miel.jpg"))); // NOI18N
        jPanel1.add(lm3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 270, 230, 160));
        jPanel1.add(lm4, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 170, 110, 250));

        lm5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ja1.jpg"))); // NOI18N
        jPanel1.add(lm5, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 180, 120, 250));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel22.setForeground(new java.awt.Color(0, 0, 255));
        jLabel22.setText("DNI :");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -60, -1, -1));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 936, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        int c;
        c = jComboBox1.getSelectedIndex();

        switch(c){
                    //visible
            case 0: 
                    this.listcolec.setVisible(true);
                    this.listcolpre.setVisible(true);
                    this.listcollar.setVisible(false);
                    this.listprecollar.setVisible(false);
                    this.listpendientes.setVisible(false);
                    this.listprependi.setVisible(false);
                    this.listanillos.setVisible(false);
                    this.listpreanillos.setVisible(false);

                   //limpiarindice
                    this.listcollar.clearSelection();
                    this.listprecollar.clearSelection();
                    this.listpendientes.clearSelection();
                    this.listprependi.clearSelection();
                    this.listanillos.clearSelection();
                    this.listpreanillos.clearSelection();
                    break;

            case 1:

                    
                    //visible
                    this.listcollar.setVisible(true);
                    this.listprecollar.setVisible(true);
                    this.listcolec.setVisible(false);
                    this.listcolpre.setVisible(false);
                    this.listpendientes.setVisible(false);
                    this.listprependi.setVisible(false);
                    this.listanillos.setVisible(false);
                    this.listpreanillos.setVisible(false);
                    //limpiar indice
                    this.listcolec.clearSelection();
                    this.listcolpre.clearSelection();
                    this.listpendientes.clearSelection();
                    this.listprependi.clearSelection();
                    this.listanillos.clearSelection();
                    this.listpreanillos.clearSelection();
                    break;
            
            case 2:
                    //visible
                    this.listpendientes.setVisible(true);
                    this.listprependi.setVisible(true);
                    this.listcollar.setVisible(false);
                    this.listprecollar.setVisible(false);
                    this.listcolec.setVisible(false);
                    this.listcolpre.setVisible(false);
                    this.listanillos.setVisible(false);
                    this.listpreanillos.setVisible(false);
                    //limpiar indice
                    this.listcollar.clearSelection();
                    this.listprecollar.clearSelection();
                    this.listcolec.clearSelection();
                    this.listcolpre.clearSelection();
                    this.listanillos.clearSelection();
                    this.listpreanillos.clearSelection();
                    break;

            case 3:
                //visible
                    this.listanillos.setVisible(true);
                    this.listpreanillos.setVisible(true);
                    this.listpendientes.setVisible(false);
                    this.listprependi.setVisible(false);
                    this.listcollar.setVisible(false);
                    this.listprecollar.setVisible(false);
                    this.listcolec.setVisible(false);
                    this.listcolpre.setVisible(false);
                  //limpiar indice
                     this.listpendientes.clearSelection();
                    this.listprependi.clearSelection();
                    this.listcollar.clearSelection();
                    this.listprecollar.clearSelection();
                    this.listcolec.clearSelection();
                    this.listcolpre.clearSelection();
                    break;

        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void listcolecValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listcolecValueChanged

     int indice;
      indice = listcolec.getSelectedIndex();
     listcolpre.setSelectedIndex(indice);
   
    }//GEN-LAST:event_listcolecValueChanged

    private void listcollarValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listcollarValueChanged
      int indice;
      indice = listcollar.getSelectedIndex();
     listprecollar.setSelectedIndex(indice);
     
    }//GEN-LAST:event_listcollarValueChanged

    private void listpendientesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listpendientesValueChanged
        int indice;
      indice = listpendientes.getSelectedIndex();
     listprependi.setSelectedIndex(indice);
   
    }//GEN-LAST:event_listpendientesValueChanged

    private void listanillosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listanillosValueChanged
       int indice;
      indice = listanillos.getSelectedIndex();
     listpreanillos.setSelectedIndex(indice);
  
    }//GEN-LAST:event_listanillosValueChanged

    private void listprecollarValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listprecollarValueChanged

        int indice;

        indice = listprecollar.getSelectedIndex();
        switch(indice){
            case 0:
                this.jTextArea1.setText("");
                this.jTextArea1.setForeground(Color.blue);
                this.jTextArea1.append("NAZTISOL :" + "PARA EL DOLOR DE ESTOMAGO \n 250ML" + "\n");
                this.lm1.setVisible(true);
                this.lm2.setVisible(false);
                this.lm3.setVisible(false);
                this.lm4.setVisible(false);
                this.lm5.setVisible(false);
                //**
                this.li1.setVisible(false);
                this.li2.setVisible(false);
                this.li3.setVisible(false);
                this.li4.setVisible(false);
                this.li5.setVisible(false);
                //**
                this.lj1.setVisible(false);
                this.lj2.setVisible(false);
                this.lj3.setVisible(false);
                this.lj4.setVisible(false);
                this.lj5.setVisible(false);
                //**
                this.lk1.setVisible(false);
                this.lk2.setVisible(false);
                this.lk3.setVisible(false);
                this.lk4.setVisible(false);
                this.lk5.setVisible(false);
                break;
            case 1:
                this.jTextArea1.setText("");
                this.jTextArea1.setForeground(Color.blue);
                this.jTextArea1.append("PARACETAMOL:" + "PARA EL DOLOR DE STOMAGO \n INCLUYE CUCHARITA " + "\n");
                this.lm1.setVisible(false);
                this.lm2.setVisible(true);
                this.lm3.setVisible(false);
                this.lm4.setVisible(false);
                this.lm5.setVisible(false);
                //**
                this.li1.setVisible(false);
                this.li2.setVisible(false);
                this.li3.setVisible(false);
                this.li4.setVisible(false);
                this.li5.setVisible(false);
                //**
                this.lj1.setVisible(false);
                this.lj2.setVisible(false);
                this.lj3.setVisible(false);
                this.lj4.setVisible(false);
                this.lj5.setVisible(false);
                //**
                this.lk1.setVisible(false);
                this.lk2.setVisible(false);
                this.lk3.setVisible(false);
                this.lk4.setVisible(false);
                this.lk5.setVisible(false);
                break;
            case 2:
                this.jTextArea1.setText("");
                this.jTextArea1.setForeground(Color.blue);
                this.jTextArea1.append("VICKMIEL :" + "ALIVIA LA GRIPE Y TOS SECA " + "\n");
                this.lm1.setVisible(false);
                this.lm2.setVisible(false);
                this.lm3.setVisible(true);
                this.lm4.setVisible(false);
                this.lm5.setVisible(false);
                //**
                this.li1.setVisible(false);
                this.li2.setVisible(false);
                this.li3.setVisible(false);
                this.li4.setVisible(false);
                this.li5.setVisible(false);
                //**
                this.lj1.setVisible(false);
                this.lj2.setVisible(false);
                this.lj3.setVisible(false);
                this.lj4.setVisible(false);
                this.lj5.setVisible(false);
                //**
                this.lk1.setVisible(false);
                this.lk2.setVisible(false);
                this.lk3.setVisible(false);
                this.lk4.setVisible(false);
                this.lk5.setVisible(false);
                break;
            case 3:
                this.jTextArea1.setText("");
                this.jTextArea1.setForeground(Color.blue);
                this.jTextArea1.append("PALTOMIEL: " + "ALIVIA LA TOS SECA \n 2 VECES AL DIA " + "\n");
                this.lm1.setVisible(false);
                this.lm2.setVisible(false);
                this.lm3.setVisible(false);
                this.lm4.setVisible(true);
                this.lm5.setVisible(false);
                //**
                this.li1.setVisible(false);
                this.li2.setVisible(false);
                this.li3.setVisible(false);
                this.li4.setVisible(false);
                this.li5.setVisible(false);
                //**
                this.lj1.setVisible(false);
                this.lj2.setVisible(false);
                this.lj3.setVisible(false);
                this.lj4.setVisible(false);
                this.lj5.setVisible(false);
                //**
                this.lk1.setVisible(false);
                this.lk2.setVisible(false);
                this.lk3.setVisible(false);
                this.lk4.setVisible(false);
                this.lk5.setVisible(false);
                break;


        }
}//GEN-LAST:event_listprecollarValueChanged

    private void listprependiValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listprependiValueChanged

        int indice;
        indice = listprependi.getSelectedIndex();
        switch(indice){
            case 0:
                this.jTextArea1.setText("");
                this.jTextArea1.setForeground(Color.magenta);
                this.jTextArea1.append("KALOS :" + "PERFUME PARA VARON 100% ELEGANTE " + "\n");
                this.lk1.setVisible(true);
                this.lk2.setVisible(false);
                this.lk3.setVisible(false);
                this.lk4.setVisible(false);
                this.lk5.setVisible(false);
                //**
                this.li1.setVisible(false);
                this.li2.setVisible(false);
                this.li3.setVisible(false);
                this.li4.setVisible(false);
                this.li5.setVisible(false);
                //**
                this.lj1.setVisible(false);
                this.lj2.setVisible(false);
                this.lj3.setVisible(false);
                this.lj4.setVisible(false);
                this.lj5.setVisible(false);
                //**
                this.lm1.setVisible(false);
                this.lm2.setVisible(false);
                this.lm3.setVisible(false);
                this.lm4.setVisible(false);
                this.lm5.setVisible(false);
                break;
            case 1:
                this.jTextArea1.setText("");
                this.jTextArea1.setForeground(Color.magenta);
                this.jTextArea1.append("URBAN :" + "PERFUME CASUAL " + "\n");
                this.lk1.setVisible(false);
                this.lk2.setVisible(true);
                this.lk3.setVisible(false);
                this.lk4.setVisible(false);
                this.lk5.setVisible(false);
                //**
                this.li1.setVisible(false);
                this.li2.setVisible(false);
                this.li3.setVisible(false);
                this.li4.setVisible(false);
                this.li5.setVisible(false);
                //**
                this.lj1.setVisible(false);
                this.lj2.setVisible(false);
                this.lj3.setVisible(false);
                this.lj4.setVisible(false);
                this.lj5.setVisible(false);
                //**
                this.lm1.setVisible(false);
                this.lm2.setVisible(false);
                this.lm3.setVisible(false);
                this.lm4.setVisible(false);
                this.lm5.setVisible(false);
                break;
            case 2:
                this.jTextArea1.setText("");
                this.jTextArea1.setForeground(Color.magenta);
                this.jTextArea1.append("SALVAJE :" + "FRAGANCIA VARONIL  " + "\n");
                this.lk1.setVisible(false);
                this.lk2.setVisible(false);
                this.lk3.setVisible(true);
                this.lk4.setVisible(false);
                this.lk5.setVisible(false);
                //**
                this.li1.setVisible(false);
                this.li2.setVisible(false);
                this.li3.setVisible(false);
                this.li4.setVisible(false);
                this.li5.setVisible(false);
                //**
                this.lj1.setVisible(false);
                this.lj2.setVisible(false);
                this.lj3.setVisible(false);
                this.lj4.setVisible(false);
                this.lj5.setVisible(false);
                //**
                this.lm1.setVisible(false);
                this.lm2.setVisible(false);
                this.lm3.setVisible(false);
                this.lm4.setVisible(false);
                this.lm5.setVisible(false);
                break;
            case 3:
                this.jTextArea1.setText("");
                this.jTextArea1.setForeground(Color.magenta);
                this.jTextArea1.append("SPORT : " + "PERFUME PARA CUALQUIER OCACION \n 10% MAS  " + "\n");
                this.lk1.setVisible(false);
                this.lk2.setVisible(false);
                this.lk3.setVisible(false);
                this.lk4.setVisible(true);
                this.lk5.setVisible(false);
                //**
                this.li1.setVisible(false);
                this.li2.setVisible(false);
                this.li3.setVisible(false);
                this.li4.setVisible(false);
                this.li5.setVisible(false);
                //**
                this.lj1.setVisible(false);
                this.lj2.setVisible(false);
                this.lj3.setVisible(false);
                this.lj4.setVisible(false);
                this.lj5.setVisible(false);
                //**
                this.lm1.setVisible(false);
                this.lm2.setVisible(false);
                this.lm3.setVisible(false);
                this.lm4.setVisible(false);
                this.lm5.setVisible(false);
                break;
            case 4:
                this.jTextArea1.setText("");
                this.jTextArea1.setForeground(Color.magenta);
                this.jTextArea1.append(" PULSO:" + "FRGANCIA QUE ENCANTA A LAS DAMAS \n " + "\n");
                this.lk1.setVisible(false);
                this.lk2.setVisible(false);
                this.lk3.setVisible(false);
                this.lk4.setVisible(false);
                this.lk5.setVisible(true);
                //**
                this.li1.setVisible(false);
                this.li2.setVisible(false);
                this.li3.setVisible(false);
                this.li4.setVisible(false);
                this.li5.setVisible(false);
                //**
                this.lj1.setVisible(false);
                this.lj2.setVisible(false);
                this.lj3.setVisible(false);
                this.lj4.setVisible(false);
                this.lj5.setVisible(false);
                //**
                this.lm1.setVisible(false);
                this.lm2.setVisible(false);
                this.lm3.setVisible(false);
                this.lm4.setVisible(false);
                this.lm5.setVisible(false);
                break;
            case 5:
                this.jTextArea1.setText("");
                this.jTextArea1.setForeground(Color.magenta);
                this.jTextArea1.append("VANIDADES:" + "PERFUME DE GRAN CALIDAD Y ELAGACIA \n " + "\n");
                this.lk1.setVisible(false);
                this.lk2.setVisible(false);
                this.lk3.setVisible(false);
                this.lk4.setVisible(false);
                this.lk5.setVisible(true);
                //**
                this.li1.setVisible(false);
                this.li2.setVisible(false);
                this.li3.setVisible(false);
                this.li4.setVisible(false);
                this.li5.setVisible(false);
                //**
                this.lj1.setVisible(false);
                this.lj2.setVisible(false);
                this.lj3.setVisible(false);
                this.lj4.setVisible(false);
                this.lj5.setVisible(false);
                //**
                this.lm1.setVisible(false);
                this.lm2.setVisible(false);
                this.lm3.setVisible(false);
                this.lm4.setVisible(false);
                this.lm5.setVisible(false);
                break;

        }
}//GEN-LAST:event_listprependiValueChanged

    private void listpreanillosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listpreanillosValueChanged
        int indice;
        indice = listpreanillos.getSelectedIndex();
        switch(indice){
            case 0:
                this.jTextArea1.setText("");
                this.jTextArea1.setForeground(Color.BLUE);
                this.jTextArea1.append("KOLINOS :" + "DEJA LOS DIENTES TOTALMENTE LIMPIOS Y GRAN FRESCURA " + "\n");
                this.lj1.setVisible(true);
                this.lj2.setVisible(false);
                this.lj3.setVisible(false);
                this.lj4.setVisible(false);
                this.lj5.setVisible(false);
                //**
                this.li1.setVisible(false);
                this.li2.setVisible(false);
                this.li3.setVisible(false);
                this.li4.setVisible(false);
                this.li5.setVisible(false);
                //**
                this.lk1.setVisible(false);
                this.lk2.setVisible(false);
                this.lk3.setVisible(false);
                this.lk4.setVisible(false);
                this.lk5.setVisible(false);
                //**
                this.lm1.setVisible(false);
                this.lm2.setVisible(false);
                this.lm3.setVisible(false);
                this.lm4.setVisible(false);
                this.lm5.setVisible(false);
                break;
            case 1:
                this.jTextArea1.setText("");
                this.jTextArea1.setForeground(Color.BLUE);
                this.jTextArea1.append("JABON :" + " TIENE GRAN OLOR 100% ANTIBACTERIANO" + "\n");
                this.lj1.setVisible(false);
                this.lj2.setVisible(true);
                this.lj3.setVisible(false);
                this.lj4.setVisible(false);
                this.lj5.setVisible(false);
                //**
                this.li1.setVisible(false);
                this.li2.setVisible(false);
                this.li3.setVisible(false);
                this.li4.setVisible(false);
                this.li5.setVisible(false);
                //**
                this.lk1.setVisible(false);
                this.lk2.setVisible(false);
                this.lk3.setVisible(false);
                this.lk4.setVisible(false);
                this.lk5.setVisible(false);
                //**
                this.lm1.setVisible(false);
                this.lm2.setVisible(false);
                this.lm3.setVisible(false);
                this.lm4.setVisible(false);
                this.lm5.setVisible(false);


                break;
            case 2:
                this.jTextArea1.setText("");
                this.jTextArea1.setForeground(Color.BLUE);
                this.jTextArea1.append("LISTERINE :" + "TE DEJA LOS DIENTES TOTAMENTE BLANCOS" + "\n");
                this.lj1.setVisible(false);
                this.lj2.setVisible(false);
                this.lj3.setVisible(true);
                this.lj4.setVisible(false);
                this.lj5.setVisible(false);
                //**
                this.li1.setVisible(false);
                this.li2.setVisible(false);
                this.li3.setVisible(false);
                this.li4.setVisible(false);
                this.li5.setVisible(false);
                //**
                this.lk1.setVisible(false);
                this.lk2.setVisible(false);
                this.lk3.setVisible(false);
                this.lk4.setVisible(false);
                this.lk5.setVisible(false);
                //**
                this.lm1.setVisible(false);
                this.lm2.setVisible(false);
                this.lm3.setVisible(false);
                this.lm4.setVisible(false);
                this.lm5.setVisible(false);
                break;
            case 3:
                this.jTextArea1.setText("");
                this.jTextArea1.setForeground(Color.BLUE);
                this.jTextArea1.append("TALCOS :" + "TE DA UNA GRAN SUAVIDAS Y AROMA A LA PIEL" + "\n");
                this.lj1.setVisible(false);
                this.lj2.setVisible(false);
                this.lj3.setVisible(false);
                this.lj4.setVisible(true);
                this.lj5.setVisible(false);
                //**
                this.li1.setVisible(false);
                this.li2.setVisible(false);
                this.li3.setVisible(false);
                this.li4.setVisible(false);
                this.li5.setVisible(false);
                //**
                this.lk1.setVisible(false);
                this.lk2.setVisible(false);
                this.lk3.setVisible(false);
                this.lk4.setVisible(false);
                this.lk5.setVisible(false);
                //**
                this.lm1.setVisible(false);
                this.lm2.setVisible(false);
                this.lm3.setVisible(false);
                this.lm4.setVisible(false);
                this.lm5.setVisible(false);
                break;
            case 4:
                this.jTextArea1.setText("");
                this.jTextArea1.setForeground(Color.BLUE);
                this.jTextArea1.append("SHAMPO :" + "TE DEJA EL CABELLO TOTALMENTE SUAVE" + "\n");
                this.lj1.setVisible(false);
                this.lj2.setVisible(false);
                this.lj3.setVisible(false);
                this.lj4.setVisible(false);
                this.lj5.setVisible(true);
                //**
                this.li1.setVisible(false);
                this.li2.setVisible(false);
                this.li3.setVisible(false);
                this.li4.setVisible(false);
                this.li5.setVisible(false);
                //**
                this.lk1.setVisible(false);
                this.lk2.setVisible(false);
                this.lk3.setVisible(false);
                this.lk4.setVisible(false);
                this.lk5.setVisible(false);
                //**
                this.lm1.setVisible(false);
                this.lm2.setVisible(false);
                this.lm3.setVisible(false);
                this.lm4.setVisible(false);
                this.lm5.setVisible(false);
                break;
            case 5:
                this.jTextArea1.setText("");
                this.jTextArea1.setForeground(Color.BLUE);
                this.jTextArea1.append("CEPILLO :" + "CEPILLO DE HILOS FLEXIBLES QUE TE DAN MEJOR CEPILLADO" + "\n");
                this.lj1.setVisible(false);
                this.lj2.setVisible(false);
                this.lj3.setVisible(false);
                this.lj4.setVisible(false);
                this.lj5.setVisible(true);
                //**
                this.li1.setVisible(false);
                this.li2.setVisible(false);
                this.li3.setVisible(false);
                this.li4.setVisible(false);
                this.li5.setVisible(false);
                //**
                this.lk1.setVisible(false);
                this.lk2.setVisible(false);
                this.lk3.setVisible(false);
                this.lk4.setVisible(false);
                this.lk5.setVisible(false);
                //**
                this.lm1.setVisible(false);
                this.lm2.setVisible(false);
                this.lm3.setVisible(false);
                this.lm4.setVisible(false);
                this.lm5.setVisible(false);
                break;
        }
}//GEN-LAST:event_listpreanillosValueChanged

    private void listcolpreValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listcolpreValueChanged
        int indice;

        indice = listcolpre.getSelectedIndex();
        switch(indice){
            case 0:
                this.jTextArea1.setText("");
                this.jTextArea1.setForeground(Color.BLUE);
                this.jTextArea1.append("PANADOL :" + "PASTILLAS PARA ALIVIAR CUALQUIER DOLOR DEL CUERPO \n DIFERNETE PRECIOS " + "\n");
                this.li1.setVisible(true);
                this.li2.setVisible(false);
                this.li3.setVisible(false);
                this.li4.setVisible(false);
                this.li5.setVisible(false);
                this.lj1.setVisible(false);
                this.lj2.setVisible(false);
                this.lj3.setVisible(false);
                this.lj4.setVisible(false);
                this.lj5.setVisible(false);
                this.lk1.setVisible(false);
                this.lk2.setVisible(false);
                this.lk3.setVisible(false);
                this.lk4.setVisible(false);
                this.lk5.setVisible(false);
                this.lm1.setVisible(false);
                this.lm2.setVisible(false);
                this.lm3.setVisible(false);
                this.lm4.setVisible(false);
                this.lm5.setVisible(false);

                break;
            case 1:
                this.jTextArea1.setText("");
                this.jTextArea1.setForeground(Color.BLUE);
                this.jTextArea1.append("PARACETAMOL:" + "PASTILLA QUE NOS ALIVIAR CUALQUIER DOLOR DE ESTOMAGO\n " + "\n");
                this.li1.setVisible(false);
                this.li2.setVisible(true);
                this.li3.setVisible(false);
                this.li4.setVisible(false);
                this.li5.setVisible(false);
                this.lj1.setVisible(false);
                this.lj2.setVisible(false);
                this.lj3.setVisible(false);
                this.lj4.setVisible(false);
                this.lj5.setVisible(false);
                this.lk1.setVisible(false);
                this.lk2.setVisible(false);
                this.lk3.setVisible(false);
                this.lk4.setVisible(false);
                this.lk5.setVisible(false);
                this.lm1.setVisible(false);
                this.lm2.setVisible(false);
                this.lm3.setVisible(false);
                this.lm4.setVisible(false);
                this.lm5.setVisible(false);
                break;
            case 2:
                this.jTextArea1.setText("");
                this.jTextArea1.setForeground(Color.BLUE);
                this.jTextArea1.append("AMOCIXILINA : PARA LA GRIPE Y DOLOR DE CABEZA" + " \n  2 TOMAS  " + "\n");
                this.li1.setVisible(false);
                this.li2.setVisible(false);
                this.li3.setVisible(true);
                this.li4.setVisible(false);
                this.li5.setVisible(false);
                this.lj1.setVisible(false);
                this.lj2.setVisible(false);
                this.lj3.setVisible(false);
                this.lj4.setVisible(false);
                this.lj5.setVisible(false);
                this.lk1.setVisible(false);
                this.lk2.setVisible(false);
                this.lk3.setVisible(false);
                this.lk4.setVisible(false);
                this.lk5.setVisible(false);
                this.lm1.setVisible(false);
                this.lm2.setVisible(false);
                this.lm3.setVisible(false);
                this.lm4.setVisible(false);
                this.lm5.setVisible(false);

                break;
            case 3:
                this.jTextArea1.setText("");
                this.jTextArea1.setForeground(Color.BLUE);
                this.jTextArea1.append("APRONAX: " + "PARA EL DOLOR MUSCULAR  " + "\n");
                this.li1.setVisible(false);
                this.li2.setVisible(false);
                this.li3.setVisible(false);
                this.li4.setVisible(true);
                this.li5.setVisible(false);
                this.lj1.setVisible(false);
                this.lj2.setVisible(false);
                this.lj3.setVisible(false);
                this.lj4.setVisible(false);
                this.lj5.setVisible(false);
                this.lk1.setVisible(false);
                this.lk2.setVisible(false);
                this.lk3.setVisible(false);
                this.lk4.setVisible(false);
                this.lk5.setVisible(false);
                this.lm1.setVisible(false);
                this.lm2.setVisible(false);
                this.lm3.setVisible(false);
                this.lm4.setVisible(false);
                this.lm5.setVisible(false);
                break;
            case 4:
                this.jTextArea1.setText("");
                this.jTextArea1.setForeground(Color.BLUE);
                this.jTextArea1.append("NAZTISOL :" + "ALIVIA LA FIEBRE \n CADA 8 HORAS" + "\n");
                this.li1.setVisible(false);
                this.li2.setVisible(false);
                this.li3.setVisible(false);
                this.li4.setVisible(false);
                this.li5.setVisible(true);
                this.lj1.setVisible(false);
                this.lj2.setVisible(false);
                this.lj3.setVisible(false);
                this.lj4.setVisible(false);
                this.lj5.setVisible(false);
                this.lk1.setVisible(false);
                this.lk2.setVisible(false);
                this.lk3.setVisible(false);
                this.lk4.setVisible(false);
                this.lk5.setVisible(false);
                this.lm1.setVisible(false);
                this.lm2.setVisible(false);
                this.lm3.setVisible(false);
                this.lm4.setVisible(false);
                this.lm5.setVisible(false);
                break;
            case 5:
                this.jTextArea1.setText("");
                this.jTextArea1.setForeground(Color.BLUE);
                this.jTextArea1.append("PONSTAN :" + "ALIVIA LOS COLOCOS MESTRUALES \n CADA 8 HORAS" + "\n");
                this.li1.setVisible(false);
                this.li2.setVisible(false);
                this.li3.setVisible(false);
                this.li4.setVisible(false);
                this.li5.setVisible(true);
                this.lj1.setVisible(false);
                this.lj2.setVisible(false);
                this.lj3.setVisible(false);
                this.lj4.setVisible(false);
                this.lj5.setVisible(false);
                this.lk1.setVisible(false);
                this.lk2.setVisible(false);
                this.lk3.setVisible(false);
                this.lk4.setVisible(false);
                this.lk5.setVisible(false);
                this.lm1.setVisible(false);
                this.lm2.setVisible(false);
                this.lm3.setVisible(false);
                this.lm4.setVisible(false);
                this.lm5.setVisible(false);
                break;
            case 6:
                this.jTextArea1.setText("");
                this.jTextArea1.setForeground(Color.BLUE);
                this.jTextArea1.append("REDOXON :" + "ALIVIA LA FIEBRE \n CADA 8 HORAS" + "\n");
                this.li1.setVisible(false);
                this.li2.setVisible(false);
                this.li3.setVisible(false);
                this.li4.setVisible(false);
                this.li5.setVisible(true);
                this.lj1.setVisible(false);
                this.lj2.setVisible(false);
                this.lj3.setVisible(false);
                this.lj4.setVisible(false);
                this.lj5.setVisible(false);
                this.lk1.setVisible(false);
                this.lk2.setVisible(false);
                this.lk3.setVisible(false);
                this.lk4.setVisible(false);
                this.lk5.setVisible(false);
                this.lm1.setVisible(false);
                this.lm2.setVisible(false);
                this.lm3.setVisible(false);
                this.lm4.setVisible(false);
                this.lm5.setVisible(false);
                break;
            case 7:
                this.jTextArea1.setText("");
                this.jTextArea1.setForeground(Color.BLUE);
                this.jTextArea1.append("PEDIACHUR :" + "PARA EL DOLOR DE LOS HUESOS EN ADULTOS \n CADA 8 HORAS" + "\n");
                this.li1.setVisible(false);
                this.li2.setVisible(false);
                this.li3.setVisible(false);
                this.li4.setVisible(false);
                this.li5.setVisible(true);
                this.lj1.setVisible(false);
                this.lj2.setVisible(false);
                this.lj3.setVisible(false);
                this.lj4.setVisible(false);
                this.lj5.setVisible(false);
                this.lk1.setVisible(false);
                this.lk2.setVisible(false);
                this.lk3.setVisible(false);
                this.lk4.setVisible(false);
                this.lk5.setVisible(false);
                this.lm1.setVisible(false);
                this.lm2.setVisible(false);
                this.lm3.setVisible(false);
                this.lm4.setVisible(false);
                this.lm5.setVisible(false);
                break;


        }
    }//GEN-LAST:event_listcolpreValueChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel li1;
    private javax.swing.JLabel li2;
    private javax.swing.JLabel li3;
    private javax.swing.JLabel li4;
    private javax.swing.JLabel li5;
    private javax.swing.JList listanillos;
    private javax.swing.JList listcolec;
    private javax.swing.JList listcollar;
    private javax.swing.JList listcolpre;
    private javax.swing.JList listpendientes;
    private javax.swing.JList listpreanillos;
    private javax.swing.JList listprecollar;
    private javax.swing.JList listprependi;
    private javax.swing.JLabel lj1;
    private javax.swing.JLabel lj2;
    private javax.swing.JLabel lj3;
    private javax.swing.JLabel lj4;
    private javax.swing.JLabel lj5;
    private javax.swing.JLabel lk1;
    private javax.swing.JLabel lk2;
    private javax.swing.JLabel lk3;
    private javax.swing.JLabel lk4;
    private javax.swing.JLabel lk5;
    private javax.swing.JLabel lm1;
    private javax.swing.JLabel lm2;
    private javax.swing.JLabel lm3;
    private javax.swing.JLabel lm4;
    private javax.swing.JLabel lm5;
    // End of variables declaration//GEN-END:variables

}
